---
title: "Logistic Regression on Telecom Churn Data - Markdown"
author: "Alexander Vaillant"
date: "9/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Environment Setup
### Import Necessary Libraries

```{r}
# Load in necessary libraries using library()
library(dplyr)
library(tidyverse)
library(caret)
library(leaps)
library(reshape2)
library(fastDummies) #Create dummy columns easily
library(MLmetrics) #Calculate F1_Score
library(plyr) # Rename columns
```

## Data Gathering
### Load Dataset into Dataframe using read.csv()

```{r}
# Import the raw dataset using read.csv()
url <- "C:/Users/tedda/Desktop/Data Science Portfolio/Machine Learning/Supervised Learning/Regression/Logistic Regression on Telecom Churn Data/Raw Datasets/churn_clean.csv"
churndata <- read.csv(url, header = TRUE)
```

## Data Preparation

```{r}
# Remove customer demographic data by indexing
churn_indexed <- churndata[c(20:50)]

# Transform categorical variables in dummy variable columns by using fastDummies::dummy_cols()
churn_dummies <- dummy_cols(churn_indexed, remove_first_dummy = TRUE, remove_selected_columns = TRUE)
names(churn_dummies)

# Rename any variables with spaces in their names by using plyr::rename()
churn_renamed <- rename(churn_dummies, replace = c("Contract_One year" = "Contract_One_Year"))
churn_renamed <- rename(churn_renamed, replace = c("Contract_Two Year" = "Contract_Two_Year"))
churn_renamed <- rename(churn_renamed, replace = c("InternetService_Fiber Optic" = "InternetService_Fiber_Optic"))
churn_renamed <- rename(churn_renamed, replace = c("PaymentMethod_Credit Card (automatic)" = "PaymentMethod_Credit_Card_(automatic)"))
churn_renamed <- rename(churn_renamed, replace = c("PaymentMethod_Electronic Check" = "PaymentMethod_Electronic_Check"))
churn_renamed <- rename(churn_renamed, replace = c("PaymentMethod_Mailed Check" = "PaymentMethod_Mailed_Check"))

# Normalize all variables by using caret::preProcess()
preproc <- preProcess(churn_renamed, method = c("range"))
churn_norm <- predict(preproc, churn_renamed)
summary(churn_norm)

# Create a correlation matrix and heatmap to identify multicollinearity by using cor(), ggplot2::ggplot(), and reshape2::melt()
cormatrix <- round(cor(churn_norm),2)
melted_cormatrix <- melt(cormatrix)
ggplot(melted_cormatrix, aes(x = Var1, y= Var2, fill = value)) + geom_tile()
cormatrix[,"Churn_Yes"]
write.csv(cormatrix,"C:/Users/tedda/Desktop/Data Science Portfolio/Machine Learning/Supervised Learning/Regression/Logistic Regression on Telecom Churn Data/Explanations/Correlation Matrix/Correlation Matrix.csv", row.names = TRUE)

# Remove Bandwidth_GB_Year from analysis as it is highly correlated with Tenure
churn_norm <- churn_norm[c(1:6,8:35)]

# Export the prepared dataset as a .csv file using write.csv()
write.csv(churn_norm,"C:/Users/tedda/Desktop/Data Science Portfolio/Machine Learning/Supervised Learning/Regression/Logistic Regression on Telecom Churn Data/Cleansed Datasets/Prepped Dataset.csv", row.names = FALSE)
```

## Exploratory Data Analysis on Initial Model

```{r}
# Create the Gross "Initial" Model
LG_GrossModel <- glm(Churn_Yes ~ ., data = churn_norm, family = "binomial")
summary(LG_GrossModel)

# Subset Regression to identify the top 5 variables affecting Churn using leaps::regsubsets()
subsets <- regsubsets(Churn_Yes ~ ., data = churn_norm, nvmax = 5)
summary(subsets)

# Create Univariate Distributions using histograms
par(mfrow = c(2,3))
InternetServiceFiberOptic_hist <- hist(churn_norm$InternetService_Fiber_Optic)
ContractOneYear_hist <- hist(churn_norm$Contract_One_Year)
ContractTwoYear_hist <- hist(churn_norm$Contract_Two_Year)
Tenure_hist <- hist(churn_norm$Tenure)
MonthlyCharge_hist <- hist(churn_norm$MonthlyCharge)
ChurnYes_hist <- hist(churn_norm$Churn_Yes)

# Create Bivariate Distrbutions using boxplot() 
par(mfrow = c(2,3))
Tenure_boxplot <- boxplot(Tenure ~ Churn_Yes, data = churn_norm)
MonthlyCharge_boxplot <- boxplot(MonthlyCharge ~ Churn_Yes, data = churn_norm)
InternetServiceFiberOptic_boxplot <- boxplot(InternetService_Fiber_Optic ~ Churn_Yes, data = churn_norm)
ContractOneYear_boxplot <- boxplot(Contract_One_Year~ Churn_Yes, data = churn_norm)
ContractTwoYear_boxplot <- boxplot(Contract_Two_Year~ Churn_Yes, data = churn_norm)

# Reduced Correlation Matrix of only top 5 variables
reduced_data <- churn_norm[c(16,5:6,18:19,22)]
reduced_cormatrix <- round(cor(reduced_data),2)
reduced_cormatrix
```

## Model Building

```{r}
# Create the Adjusted "Reduced" Model based on the 5 variables found above
LG_AdjustedModel <- glm(Churn_Yes ~ Tenure + MonthlyCharge + Contract_One_Year + Contract_Two_Year + InternetService_Fiber_Optic, churn_norm, family = "binomial")
summary(LG_AdjustedModel)

# Extract Coefficients of the Adjusted Model using coef()
coef(LG_AdjustedModel)

# Create the 4-variable reduced model based on the subsets found
LG_Reduced4Model <- glm(Churn_Yes ~ Tenure + MonthlyCharge + Contract_One_Year + Contract_Two_Year, churn_norm, family = "binomial")
summary(LG_Reduced4Model)
```

## Save and Load Model

```{r}
# Save and Load 5-variable Model
var5_model_url <- "C:/Users/tedda/Desktop/Data Science Portfolio/Machine Learning/Supervised Learning/Regression/Logistic Regression on Telecom Churn Data/Exported Models/TelecomLogisticRegressionModel5Variables.rds"
saveRDS(LG_AdjustedModel, var5_model_url)
LG_AdjustedModel <- readRDS(var5_model_url)

# Save and Load 4-variable Model
var4_model_url <- "C:/Users/tedda/Desktop/Data Science Portfolio/Machine Learning/Supervised Learning/Regression/Logistic Regression on Telecom Churn Data/Exported Models/TelecomLogisticRegressionModel4Variables.rds"
saveRDS(LG_Reduced4Model, var4_model_url)
LG_Reduced4Model <- readRDS(var4_model_url)
```

## Model Evaluation

```{r}
# Confusion Matrix for Gross Model with all variables
LGmodelGPred <- round(predict(LG_GrossModel, churn_norm, type = "response"))
LGmodelG <- confusionMatrix(as.factor(LGmodelGPred), as.factor(churn_norm$Churn))
LGmodelG

# Confusion Matrix for Adjusted Model with all variables
LGmodelAPred <- round(predict(LG_AdjustedModel, churn_norm, type = "response"))
LGmodelA <- confusionMatrix(as.factor(LGmodelAPred), as.factor(churn_norm$Churn_Yes))
LGmodelA

# Confusion Matrix for Reduced-4 variable Model with all variables
LGmodel4Pred <- round(predict(LG_Reduced4Model, churn_norm, type = "response"))
LGmodel4 <- confusionMatrix(as.factor(LGmodel4Pred), as.factor(churn_norm$Churn_Yes))
LGmodel4

# Calculate F1_Score of Gross Model
pred <- ifelse(LG_GrossModel$fitted.values < 0.5, 0, 1)
F1_Score(y_pred = pred, y_true = churn_norm$Churn_Yes, positive = "0")

# Calculate F1_Score of Adjusted Model
pred <- ifelse(LG_AdjustedModel$fitted.values < 0.5, 0, 1)
F1_Score(y_pred = pred, y_true = churn_norm$Churn_Yes, positive = "0")

# Calculate F1_Score of Reduced-4 variable Model
pred <- ifelse(LG_Reduced4Model$fitted.values < 0.5, 0, 1)
F1_Score(y_pred = pred, y_true = churn_norm$Churn_Yes, positive = "0")
```